name = "QPModelCPLEX"
uuid = "a53098ac-c15a-4696-bee0-14caaca04665"
authors = ["Geoffroy Leconte <gleconte50@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CPLEX = "a076750e-1247-5638-91d2-ce28b192dca0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
SolverTools = "b5612192-2639-5dc1-abfe-fbedd65fab29"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
QuadraticModels = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
